# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wrapper.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(422, 347)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ResamplerList = QtWidgets.QListWidget(self.centralwidget)
        self.ResamplerList.setObjectName("ResamplerList")
        self.verticalLayout.addWidget(self.ResamplerList)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AddResamplerButton = QtWidgets.QPushButton(self.frame)
        self.AddResamplerButton.setObjectName("AddResamplerButton")
        self.horizontalLayout.addWidget(self.AddResamplerButton)
        self.RemoveResamplerButton = QtWidgets.QPushButton(self.frame)
        self.RemoveResamplerButton.setObjectName("RemoveResamplerButton")
        self.horizontalLayout.addWidget(self.RemoveResamplerButton)
        self.verticalLayout.addWidget(self.frame)
        self.WrapButton = QtWidgets.QPushButton(self.centralwidget)
        self.WrapButton.setObjectName("WrapButton")
        self.verticalLayout.addWidget(self.WrapButton)
        self.ExitButton = QtWidgets.QPushButton(self.centralwidget)
        self.ExitButton.setObjectName("ExitButton")
        self.verticalLayout.addWidget(self.ExitButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Resampler Wrapper for Linux"))
        self.AddResamplerButton.setText(_translate("MainWindow", "Add"))
        self.RemoveResamplerButton.setText(_translate("MainWindow", "Remove selected"))
        self.WrapButton.setText(_translate("MainWindow", "Wrap"))
        self.ExitButton.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
